# Generated by Django 4.1.3 on 2022-12-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillup', '0003_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
